
/**
* Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* lundi 16 octobre 2017 17 h 34 CEST
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
