
/**
* BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* lundi 16 octobre 2017 17 h 34 CEST
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankHelper.type ();
  }

}
