interface Bank
{
  string createAccount();
  void deposit(in float amount, in string id_account);
  void withdrawal(in float amount, in string id_account);
  float getBalance(in string id_account);
  void intraTransfer(in string id_src, in string id_dst, in float amount);
  void interTransfer(in string id_src, in string id_dst, in string bank_id, in float amount);
0};
