
/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* lundi 16 octobre 2017 17 h 34 CEST
*/

public interface BankOperations 
{

  // string echoString(in string mesg);
  int echoString (int mesg);
} // interface BankOperations
